### ISSUE TITLE
Debug python 3.x

### ISSUE THREAD

**Issue by CodingJonas** [pybee/bugjar#21]
I work under Ubuntu 14.04 and try to debug my python code written in python 3. Is there a possibility to debug python 3?

**Comment by freakboy3742** [comment]
At present, probably not. Bugjar is in a very early prototype stage, and I've been distracted from working on it by some other related projects. If you want to submit a patch for Python 3 compatibility, I'll happily merge it; but Bugjar isn't really even ready for serious Python 2 debugging, let along Python 3.

Closing this on the basis that there isn't anything specifically actionable in this report; to the extent "support Python 3" is a feature request, that's already covered by #7.

**Comment by kevin0311** [comment]
You should put right up front  on your site and documentation that that this doesn't work with Python 3...that would save some newer folks a lot of wasted time.

**Comment by freakboy3742** [comment]
@kevin0311 Thanks for the feedback. This is a project that needs a lot of work - I've been distracted by some other things along the way.
